# Generated by Django 2.2 on 2019-07-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOA_app', '0002_auto_20190723_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_Line1_b',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_Line1_c',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_Line1_csr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_Line1_d',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_Line1_o',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_Line1_s',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_b',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_c',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_csr',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_o',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Address_s',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='City_b',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='City_c',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='City_csr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='City_d',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='City_o',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='City_s',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='CnF_Charges',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Country_b',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Country_c',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Country_csr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Country_d',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Country_o',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Country_s',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Customer_Name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Freight_Charges',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Insurance_Charges',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='List_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='SO_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='State_b',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='State_c',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='State_d',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='State_o',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='State_s',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='TRX_Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Transaction_Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='Unit_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='ZIP_b',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='ZIP_c',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='ZIP_csr',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='ZIP_d',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='ZIP_o',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sale_order_summery_v',
            name='ZIP_s',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
