from django.db import models
from SOA_app.models import *
# Create your models here.

class sale_order_summery_v(models.Model):
    Id = models.IntegerField(primary_key=True)
    SO_Line_Number = models.CharField(max_length=32,null=True)
    SO_Line_Shipment = models.CharField(max_length=32,null=True)
    Request_DATE = models.DateField()
    Schedule_Ship_Date = models.DateField()
    Promise_Date = models.DateField()
    Item_Number = models.CharField(max_length=32,null=True)
    TRX_Quantity = models.IntegerField(null=True)
    Quantity = models.IntegerField(null=True)
    List_Price = models.FloatField(null=True)
    Accounting_Rule = models.CharField(max_length=64,null=True)
    Transaction_Amount = models.FloatField(null=True)
    Customer_Item_code = models.CharField(max_length=32,null=True)
    Discount_Code1 = models.CharField(max_length=32,null=True)
    Discount_Amount1 = models.FloatField(null=True)
    Discount_Code2 = models.CharField(max_length=32,null=True)
    Discount_Amount2 = models.FloatField(null=True)
    Discount_Code3 = models.CharField(max_length=32,null=True)
    Discount_Amount3 = models.FloatField(null=True)
    Unit_Price = models.FloatField(null=True)
    Freight_Charges = models.FloatField(null=True)
    Insurance_Charges = models.FloatField(null=True)
    CnF_Charges = models.FloatField(null=True)
    Tax_Classification_Code1 = models.CharField(max_length=32,null=True)
    Tax_Amount1 = models.FloatField(null=True)
    Tax_Classification_Code2 = models.CharField(max_length=32,null=True)
    Tax_Amount2 = models.FloatField(null=True)
    Tax_Classification_Code3 = models.CharField(max_length=32,null=True)
    Tax_Amount3 = models.FloatField(null=True)
    Ship_To_Customer_Name = models.CharField(max_length=256,null=True)
    Deliver_To_Customer_Name = models.CharField(max_length=256,null=True)
    Shipping_Instruction = models.CharField(max_length=256,null=True)
    Freight_Carrier = models.CharField(max_length=32,null=True)
    Freight_Term = models.CharField(max_length=32,null=True)
    Inco_Term = models.CharField(max_length=32,null=True)
    Locator_Code = models.CharField(max_length=64,null=True)
    Payment_Method = models.CharField(max_length=32,null=True)
    Payment_Term = models.CharField(max_length=32,null=True)
    Price_List_Code = models.CharField(max_length=32,null=True)
    Sales_Channel = models.CharField(max_length=32,null=True)
    Sales_Person = models.CharField(max_length=32,null=True)
    Shipping_Method = models.CharField(max_length=64,null=True)
    CSR_Code = models.CharField(max_length=32,null=True)
    TRX_UOM_Code = models.CharField(max_length=32,null=True)
    HS_CODE = models.CharField(max_length=32,null=True)
    Customer_Name =models.CharField(max_length=64,null=True)
    Customer_Code = models.CharField(max_length=32,null=True)
    Customer_Address_Code = models.CharField(max_length=32,null=True)
    SO_Number = models.CharField(max_length=32,null=True)
    SO_STATUS = models.CharField(max_length=32,null=True)
    SO_Type = models.CharField(max_length=32,null=True)
    SO_DATE = models.DateField(null=True)
    Currency =  models.CharField(max_length=64,null=True)
    Customer_PO = models.CharField(max_length=64,null=True)
    Remark = models.CharField(max_length=256,null=True)
    Description = models.CharField(max_length=256,null=True)
    OU_Organization_Name = models.CharField(max_length=64, null=True)
    INV_Organization_Name = models.CharField(max_length=64, null=True)
    Subinventory_Name = models.CharField(max_length=64, null=True)
    Address_o = models.CharField(max_length=64,null=True)
    Address_Line1_o = models.CharField(max_length=128,null=True)
    Address_Line2_o = models.CharField(max_length=128, null=True)
    Address_Line3_o = models.CharField(max_length=128, null=True)
    City_o = models.CharField(max_length=32,null=True)
    District_o = models.CharField(max_length=32, null=True)
    County_o =  models.CharField(max_length=32, null=True)
    State_o =  models.CharField(max_length=32,null=True)
    Country_o =  models.CharField(max_length=32,null=True)
    ZIP_o  = models.CharField(max_length=16,null=True)
    Address_c = models.CharField(max_length=64,null=True)
    Address_Line1_c = models.CharField(max_length=128,null=True)
    Address_Line2_c = models.CharField(max_length=128, null=True)
    Address_Line3_c = models.CharField(max_length=128, null=True)
    City_c = models.CharField(max_length=32,null=True)
    District_c = models.CharField(max_length=32, null=True)
    County_c =  models.CharField(max_length=32, null=True)
    State_c =  models.CharField(max_length=32,null=True)
    Country_c =  models.CharField(max_length=32,null=True)
    ZIP_c  = models.CharField(max_length=16,null=True)

    Address_b = models.CharField(max_length=64,null=True)
    Address_Line1_b = models.CharField(max_length=128,null=True)
    Address_Line2_b = models.CharField(max_length=128, null=True)
    Address_Line3_b = models.CharField(max_length=128, null=True)
    City_b = models.CharField(max_length=32,null=True)
    District_b = models.CharField(max_length=32, null=True)
    County_b =  models.CharField(max_length=32, null=True)
    State_b =  models.CharField(max_length=32,null=True)
    Country_b =  models.CharField(max_length=32,null=True)
    ZIP_b  = models.CharField(max_length=16,null=True)

    Address_d = models.CharField(max_length=64,unique=True)
    Address_Line1_d = models.CharField(max_length=128,null=True)
    Address_Line2_d = models.CharField(max_length=128, null=True)
    Address_Line3_d = models.CharField(max_length=128, null=True)
    City_d = models.CharField(max_length=32,null=True)
    District_d = models.CharField(max_length=32, null=True)
    County_d =  models.CharField(max_length=32, null=True)
    State_d =  models.CharField(max_length=32,null=True)
    Country_d =  models.CharField(max_length=32,null=True)
    ZIP_d  = models.CharField(max_length=16,null=True)

    Mobile1_b1 =  models.CharField(max_length=16,null=True)
    Mobile2_b1 = models.CharField(max_length=16,null=True)
    Phone1_b2  =  models.CharField(max_length=16,null=True)
    Phone2_b2  = models.CharField(max_length=16,null=True)
    Mobile1_b2  =  models.CharField(max_length=16,null=True)
    Mobile2_b2  = models.CharField(max_length=16,null=True)
    Phone1_o1  =  models.CharField(max_length=16,null=True)
    Phone2_o1  =  models.CharField(max_length=16,null=True)
    Mobile1_o1  =  models.CharField(max_length=16,null=True)
    Mobile2_o1  =  models.CharField(max_length=16,null=True)
    Phone1_o2  =  models.CharField(max_length=16,null=True)
    Phone2_o2  =  models.CharField(max_length=16,null=True)
    Mobile1_o2  =  models.CharField(max_length=16,null=True)
    Mobile2_o2  =  models.CharField(max_length=16,null=True)

    Address_s = models.CharField(max_length=64,null=True)
    Address_Line1_s = models.CharField(max_length=128,null=True)
    Address_Line2_s = models.CharField(max_length=128, null=True)
    Address_Line3_s = models.CharField(max_length=128, null=True)
    City_s = models.CharField(max_length=32,null=True)
    District_s = models.CharField(max_length=32, null=True)
    County_s =  models.CharField(max_length=32, null=True)
    State_s =  models.CharField(max_length=32,null=True)
    Country_s =  models.CharField(max_length=32,null=True)
    ZIP_s  = models.CharField(max_length=16,null=True)

    Employee_FirstName_sp = models.CharField(max_length=256, null=True)
    Employee_LastName_sp =models.CharField(max_length=256, null=True)
    Email_sp = models.CharField(max_length=64, null=True)
    Contact_No_sp  = models.CharField(max_length=64, null=True)

    Employee_FirstName_csr = models.CharField(max_length=256, null=True)
    Employee_LastName_csr = models.CharField(max_length=256, null=True)
    Email_csr = models.CharField(max_length=64, null=True)
    Contact_No_csr  = models.CharField(max_length=64, null=True)
    Address_csr = models.CharField(max_length=64,null=True)

    Address_Line1_csr = models.CharField(max_length=128,null=True)
    Address_Line2_csr = models.CharField(max_length=128, null=True)
    Address_Line3_csr = models.CharField(max_length=128, null=True)
    City_csr = models.CharField(max_length=32,null=True)
    County_csr =  models.CharField(max_length=32, null=True)
    Country_csr =  models.CharField(max_length=32,null=True)
    ZIP_csr  = models.CharField(max_length=16,null=True)
    Total = models.FloatField()
    class Meta:
        db_table = "sale_order_summery_v"
